## config
data_source = 'local'
## Input Raw data

train_data_path = '/Users/apal/Documents/GitHub/ML_template/data/Bank_Personal_Loan_Modelling.csv'
test_data_path = '/Users/apal/Documents/GitHub/ML_template/data/Bank_Personal_Loan_Modelling.csv'
##Output Prediction
model_prediction = '../data/prediction/prediction.csv'

## Pipeline feature

feature_path = 'model_features/train_features.pkl'
model_weight_path = 'model_weights/final_model.pkl'

## Columns
feat_col = "weights/pipeline/cols.pkl"
